source('sanitizeCovr.R')

test_that('1 recipe makefile', {
  job <- list(recipe(target='target.Rdata', depends=c('dep1', 'dep2'), build='buildCmd', clean='cleanCmd'))
  res <- makefile(job, fileName=NULL)

  if (.Platform$OS.type == 'unix') {
    res <- sanitizeCovr(res)
    expect_equal(res, c('# Generated by maker: do not edit by hand',
                        'R=R --no-save --no-restore --quiet',
                        'RM=rm',
                        '',
                        'all: target.Rdata',
                        '\t',
                        'target.Rdata: dep1 dep2',
                        '\tbuildCmd',
                        'clean: ',
                        '\tcleanCmd',
                        'Makefile: Makefile.R',
                        '\techo \'{\\n\'\\',
                        '\t\'    params <- NULL\\n\'\\',
                        '\t\'    source("Makefile.R")\\n\'\\',
                        '\t\'}\\n\' | $(R)'))
  } else {
    expect_equal(res, c('# Generated by maker: do not edit by hand',
                        'R=R --no-save --no-restore --quiet',
                        'RM=del',
                        '',
                        'all: target.Rdata',
                        '\t',
                        'target.Rdata: dep1 dep2',
                        '\tbuildCmd',
                        'clean: ',
                        '\tcleanCmd',
                        'Makefile: Makefile.R',
                        '\t(echo {&echo   params ^<- NULL&echo   source^("Makefile.R"^)&echo }) | $(R)'))
  }
})

test_that('not all in makefile', {
  job <- list(recipe(target='target.Rdata', depends=c('dep1', 'dep2'), build='buildCmd', clean='cleanCmd'))
  res <- makefile(job, fileName=NULL, all=FALSE)
  res <- sanitizeCovr(res)
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=R --no-save --no-restore --quiet',
                      'RM=rm',
                      '',
                      'target.Rdata: dep1 dep2',
                      '\tbuildCmd',
                      'clean: ',
                      '\tcleanCmd',
                      'Makefile: Makefile.R',
                      '\techo \'{\\n\'\\',
                      '\t\'    params <- NULL\\n\'\\',
                      '\t\'    source("Makefile.R")\\n\'\\',
                      '\t\'}\\n\' | $(R)'))
})

test_that('not clean in makefile', {
  job <- list(recipe(target='target.Rdata', depends=c('dep1', 'dep2'), build='buildCmd', clean='cleanCmd'))
  res <- makefile(job, fileName=NULL, clean=FALSE)
  res <- sanitizeCovr(res)
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=R --no-save --no-restore --quiet',
                      'RM=rm',
                      '',
                      'all: target.Rdata',
                      '\t',
                      'target.Rdata: dep1 dep2',
                      '\tbuildCmd',
                      'Makefile: Makefile.R',
                      '\techo \'{\\n\'\\',
                      '\t\'    params <- NULL\\n\'\\',
                      '\t\'    source("Makefile.R")\\n\'\\',
                      '\t\'}\\n\' | $(R)'))
})

test_that('not Makefile in makefile', {
  job <- list(recipe(target='target.Rdata', depends=c('dep1', 'dep2'), build='buildCmd', clean='cleanCmd'))
  res <- makefile(job, fileName=NULL, makefile=FALSE)
  res <- sanitizeCovr(res)
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=R --no-save --no-restore --quiet',
                      'RM=rm',
                      '',
                      'all: target.Rdata',
                      '\t',
                      'target.Rdata: dep1 dep2',
                      '\tbuildCmd',
                      'clean: ',
                      '\tcleanCmd'))
})

test_that('custom vars in makefile', {
  job <- list(recipe(target='target.Rdata', depends=c('dep1', 'dep2'), build='buildCmd', clean='cleanCmd'))
  res <- makefile(job, fileName=NULL, vars=c(CPP='gcc'))
  res <- sanitizeCovr(res)
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=R --no-save --no-restore --quiet',
                      'RM=rm',
                      'CPP=gcc',
                      '',
                      'all: target.Rdata',
                      '\t',
                      'target.Rdata: dep1 dep2',
                      '\tbuildCmd',
                      'clean: ',
                      '\tcleanCmd',
                      'Makefile: Makefile.R',
                      '\techo \'{\\n\'\\',
                      '\t\'    params <- NULL\\n\'\\',
                      '\t\'    source("Makefile.R")\\n\'\\',
                      '\t\'}\\n\' | $(R)'))
})


test_that('redefined vars in makefile', {
  job <- list(recipe(target='target.Rdata', depends=c('dep1', 'dep2'), build='buildCmd', clean='cleanCmd'))
  res <- makefile(job, fileName=NULL, vars=c(R='MyR', CPP='gcc'))
  res <- sanitizeCovr(res)
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=MyR',
                      'RM=rm',
                      'CPP=gcc',
                      '',
                      'all: target.Rdata',
                      '\t',
                      'target.Rdata: dep1 dep2',
                      '\tbuildCmd',
                      'clean: ',
                      '\tcleanCmd',
                      'Makefile: Makefile.R',
                      '\techo \'{\\n\'\\',
                      '\t\'    params <- NULL\\n\'\\',
                      '\t\'    source("Makefile.R")\\n\'\\',
                      '\t\'}\\n\' | $(R)'))
})

test_that('multiple target recipe makefile', {
  job <- list(recipe(target=c('target.pdf', 'target.docx'),
                     depends=c('dep1', 'dep2'),
                     build='buildCmd',
                     clean='cleanCmd'))
  res <- makefile(job, fileName=NULL)
  res <- sanitizeCovr(res)
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=R --no-save --no-restore --quiet',
                      'RM=rm',
                      '',
                      'all: target.pdf target.docx',
                      '\t',
                      'target%pdf target%docx: dep1 dep2',
                      '\tbuildCmd',
                      'clean: ',
                      '\tcleanCmd',
                      'Makefile: Makefile.R',
                      '\techo \'{\\n\'\\',
                      '\t\'    params <- NULL\\n\'\\',
                      '\t\'    source("Makefile.R")\\n\'\\',
                      '\t\'}\\n\' | $(R)'))
})

test_that('makefile with tasks', {
  job <- list(recipe(target=c('target1.pdf', 'target1.docx'),
                     depends=c('dep1.1', 'dep1.2'),
                     build='buildCmd1',
                     clean='cleanCmd1',
                     task='task1'),
              recipe(target=c('target2.pdf', 'target2.docx'),
                     depends=c('dep2.1', 'dep2.2'),
                     build='buildCmd2',
                     clean='cleanCmd2',
                     task='task2'),
              recipe(target=c('target3.pdf', 'target3.docx'),
                     depends=c('dep3.1', 'dep3.2'),
                     build='buildCmd3',
                     clean='cleanCmd3'))
  res <- makefile(job, fileName=NULL)
  res <- sanitizeCovr(res)
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=R --no-save --no-restore --quiet',
                      'RM=rm',
                      '',
                      'all: task1 task2 target3.pdf target3.docx',
                      '\t',
                      'task1: target1.pdf target1.docx',
                      '\t',
                      'task2: target2.pdf target2.docx',
                      '\t',
                      'target1%pdf target1%docx: dep1.1 dep1.2',
                      '\tbuildCmd1',
                      'target2%pdf target2%docx: dep2.1 dep2.2',
                      '\tbuildCmd2',
                      'target3%pdf target3%docx: dep3.1 dep3.2',
                      '\tbuildCmd3',
                      'clean: ',
                      '\tcleanCmd1',
                      '\tcleanCmd2',
                      '\tcleanCmd3',
                      'Makefile: Makefile.R',
                      '\techo \'{\\n\'\\',
                      '\t\'    params <- NULL\\n\'\\',
                      '\t\'    source("Makefile.R")\\n\'\\',
                      '\t\'}\\n\' | $(R)'))
})
