test_that('1 recipe makefile', {
  job <- list(recipe(target='target.Rdata', depends=c('dep1', 'dep2'), build='buildCmd', clean='cleanCmd'))
  res <- makefile(job, fileName=NULL)
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=R --no-save --no-restore --quiet',
                      'RM=rm',
                      '',
                      'all: target.Rdata',
                      '\t',
                      'target.Rdata: dep1 dep2',
                      '\tbuildCmd',
                      'clean: ',
                      '\tcleanCmd',
                      'Makefile: Makefile.R',
                      '\techo \'source("Makefile.R")\\n\' | $(R)'))
})

test_that('not all in makefile', {
  job <- list(recipe(target='target.Rdata', depends=c('dep1', 'dep2'), build='buildCmd', clean='cleanCmd'))
  res <- makefile(job, fileName=NULL, all=FALSE)
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=R --no-save --no-restore --quiet',
                      'RM=rm',
                      '',
                      'target.Rdata: dep1 dep2',
                      '\tbuildCmd',
                      'clean: ',
                      '\tcleanCmd',
                      'Makefile: Makefile.R',
                      '\techo \'source("Makefile.R")\\n\' | $(R)'))
})

test_that('not clean in makefile', {
  job <- list(recipe(target='target.Rdata', depends=c('dep1', 'dep2'), build='buildCmd', clean='cleanCmd'))
  res <- makefile(job, fileName=NULL, clean=FALSE)
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=R --no-save --no-restore --quiet',
                      'RM=rm',
                      '',
                      'all: target.Rdata',
                      '\t',
                      'target.Rdata: dep1 dep2',
                      '\tbuildCmd',
                      'Makefile: Makefile.R',
                      '\techo \'source("Makefile.R")\\n\' | $(R)'))
})

test_that('not Makefile in makefile', {
  job <- list(recipe(target='target.Rdata', depends=c('dep1', 'dep2'), build='buildCmd', clean='cleanCmd'))
  res <- makefile(job, fileName=NULL, makefile=FALSE)
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=R --no-save --no-restore --quiet',
                      'RM=rm',
                      '',
                      'all: target.Rdata',
                      '\t',
                      'target.Rdata: dep1 dep2',
                      '\tbuildCmd',
                      'clean: ',
                      '\tcleanCmd'))
})

test_that('custom vars in makefile', {
  job <- list(recipe(target='target.Rdata', depends=c('dep1', 'dep2'), build='buildCmd', clean='cleanCmd'))
  res <- makefile(job, fileName=NULL, vars=c(CPP='gcc'))
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=R --no-save --no-restore --quiet',
                      'RM=rm',
                      'CPP=gcc',
                      '',
                      'all: target.Rdata',
                      '\t',
                      'target.Rdata: dep1 dep2',
                      '\tbuildCmd',
                      'clean: ',
                      '\tcleanCmd',
                      'Makefile: Makefile.R',
                      '\techo \'source("Makefile.R")\\n\' | $(R)'))
})


test_that('redefined vars in makefile', {
  job <- list(recipe(target='target.Rdata', depends=c('dep1', 'dep2'), build='buildCmd', clean='cleanCmd'))
  res <- makefile(job, fileName=NULL, vars=c(R='MyR', CPP='gcc'))
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=MyR',
                      'RM=rm',
                      'CPP=gcc',
                      '',
                      'all: target.Rdata',
                      '\t',
                      'target.Rdata: dep1 dep2',
                      '\tbuildCmd',
                      'clean: ',
                      '\tcleanCmd',
                      'Makefile: Makefile.R',
                      '\techo \'source("Makefile.R")\\n\' | $(R)'))
})

test_that('multiple target recipe makefile', {
  job <- list(recipe(target=c('target.pdf', 'target.docx'),
                     depends=c('dep1', 'dep2'),
                     build='buildCmd',
                     clean='cleanCmd'))
  res <- makefile(job, fileName=NULL)
  expect_equal(res, c('# Generated by maker: do not edit by hand',
                      'R=R --no-save --no-restore --quiet',
                      'RM=rm',
                      '',
                      'all: target.pdf target.docx',
                      '\t',
                      'target%pdf target%docx: dep1 dep2',
                      '\tbuildCmd',
                      'clean: ',
                      '\tcleanCmd',
                      'Makefile: Makefile.R',
                      '\techo \'source("Makefile.R")\\n\' | $(R)'))
})
