.defaultVars <- c(Rcode='R --no-save --no-restore --quiet -e',
                  RM='rm')

#' @export
#' @import assertthat
makefile <- function(job=list(),
                     fileName='Makefile',
                     vars=NULL,
                     all=TRUE,
                     clean=TRUE,
                     makefile=TRUE) {
  assert_that(is.list(job))
  assert_that(all(vapply(job, is.recipe, logical(1))))
  assert_that(is.null(fileName) || is.string(fileName))
  if (!is.null(vars)) {
    assert_that(is.character(vars))
    assert_that(!is.null(names(vars)))
    assert_that(is.character(names(vars)))
    assert_that(all(names(vars) != ""))
  }
  assert_that(is.flag(all))
  assert_that(is.flag(clean))
  assert_that(is.flag(makefile))

  if (all) {
    targets <- unlist(lapply(job, function(recipe) recipe$target))
    allRecipe <- recipe(target='all',
                        depends=targets,
                        build=NULL)
    job <- c(list(allRecipe), job)
  }

  if (clean) {
    cleans <- lapply(job, function(recipe) recipe[['clean']])
    if (!is.null(cleans) && length(cleans) > 0) {
      cleanRecipe <- recipe(target='clean',
                            depends=NULL,
                            build=unlist(cleans))
      job <- c(job, list(cleanRecipe))
    }
  }

  if (makefile) {
    makefileRecipe <- rRecipe(target='Makefile', script='Makefile.R')
    job <- c(job, list(makefileRecipe))
  }

  v <- .defaultVars
  v[names(vars)] <- vars
  preambleRows <- c('# Generated by maker: do not edit by hand',
                    paste0(names(v), '=', v))

  recipeRows <- unlist(lapply(job, function(recipe) {
    c(paste0(recipe$target, ': ', paste(recipe$depends, collapse=' ')),
      paste0('\t', recipe$build))
  }))

  rows <- c(preambleRows, '', recipeRows)
  if (!is.null(fileName)) {
    cat(rows, sep='\n', file=fileName)
  } else {
    return(rows)
  }
}
